"""manual invoice columns

Revision ID: c604f935f71c
Revises: b49e23560392
Create Date: 2026-06-06 22:27:51.628259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c604f935f71c'
down_revision: Union[str, Sequence[str], None] = 'b49e23560392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('invoices', sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('invoices', sa.Column('is_edited_manually', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('invoices', 'establishment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'source_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'source_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('invoices', 'establishment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoices', 'is_edited_manually')
    op.drop_column('invoices', 'is_manual')
    op.drop_column('invoice_items', 'is_manual')
    # ### end Alembic commands ###
