"""manual establishment columns

Revision ID: d40c2ea4dc57
Revises: c604f935f71c
Create Date: 2026-06-06 22:38:19.988747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40c2ea4dc57'
down_revision: Union[str, Sequence[str], None] = 'c604f935f71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('establishments', 'business_tin',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('establishments', 'business_tin',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('establishments', 'is_manual')
    # ### end Alembic commands ###
