"""add_soft_delete_to_tables

Revision ID: 633007dbd60a
Revises: c01280438a04
Create Date: 2026-05-18 00:04:07.292081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633007dbd60a'
down_revision: Union[str, Sequence[str], None] = 'c01280438a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('invoice_items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'deleted_at')
    op.drop_column('invoice_items', 'deleted_at')
    op.drop_column('establishments', 'deleted_at')
    # ### end Alembic commands ###
