"""create_ai_interactions_table

Revision ID: 05101506423d
Revises: 28eb5bc32122
Create Date: 2026-05-28 10:35:15.321174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05101506423d'
down_revision: Union[str, Sequence[str], None] = '28eb5bc32122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GEMINI', name='aiproviderenum', native_enum=False, length=100), nullable=False),
    sa.Column('task_type', sa.Enum('PRODUCT_NORMALIZATION', name='aitasktypeenum', native_enum=False, length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='aiinteractionstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interactions_provider'), 'ai_interactions', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_interactions_task_type'), 'ai_interactions', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_interactions_user_id'), 'ai_interactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_establishment_id'), 'invoices', ['establishment_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('USERS_READ', 'USERS_CREATE', 'USERS_UPDATE', 'USERS_DELETE', 'INVOICES_READ', 'INVOICES_EXTRACT', 'INVOICE_ITEMS_READ', 'ROLES_READ', 'ROLES_CREATE', 'ROLES_UPDATE', 'ROLES_DELETE', 'ROLES_ASSIGN', 'ESTABLISHMENTS_READ', 'ESTABLISHMENTS_CREATE', 'ESTABLISHMENTS_UPDATE', 'ESTABLISHMENTS_DELETE', name='permissionenum', native_enum=False, length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.alter_column('permissions', 'name',
               existing_type=sa.Enum('USERS_READ', 'USERS_CREATE', 'USERS_UPDATE', 'USERS_DELETE', 'INVOICES_READ', 'INVOICES_EXTRACT', 'INVOICE_ITEMS_READ', 'ROLES_READ', 'ROLES_CREATE', 'ROLES_UPDATE', 'ROLES_DELETE', 'ROLES_ASSIGN', 'ESTABLISHMENTS_READ', 'ESTABLISHMENTS_CREATE', 'ESTABLISHMENTS_UPDATE', 'ESTABLISHMENTS_DELETE', name='permissionenum', native_enum=False, length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_establishment_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_ai_interactions_user_id'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_task_type'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_provider'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    # ### end Alembic commands ###
