"""Add product categorization tables

Revision ID: 25163688ecf3
Revises: 05101506423d
Create Date: 2026-05-31 19:19:20.882127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25163688ecf3'
down_revision: Union[str, Sequence[str], None] = '05101506423d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'parent_id')
    )
    op.create_index(op.f('ix_product_categories_parent_id'), 'product_categories', ['parent_id'], unique=False)
    op.create_table('canonical_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_description', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('quantity_label', sa.String(length=50), nullable=True),
    sa.Column('variant', sa.String(length=255), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('measure_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_products_brand'), 'canonical_products', ['brand'], unique=False)
    op.create_index(op.f('ix_canonical_products_category_id'), 'canonical_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_canonical_products_fingerprint'), 'canonical_products', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_canonical_products_normalized_name'), 'canonical_products', ['normalized_name'], unique=False)
    op.create_table('user_product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('custom_slug', sa.String(length=255), nullable=True),
    sa.Column('custom_parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_parent_id'], ['user_product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_user_category')
    )
    op.create_index(op.f('ix_user_product_categories_category_id'), 'user_product_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_user_product_categories_custom_parent_id'), 'user_product_categories', ['custom_parent_id'], unique=False)
    op.create_index(op.f('ix_user_product_categories_user_id'), 'user_product_categories', ['user_id'], unique=False)
    op.create_table('user_product_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('canonical_product_id', sa.Integer(), nullable=False),
    sa.Column('custom_category_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('custom_brand', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'canonical_product_id', name='uq_user_override')
    )
    op.create_index(op.f('ix_user_product_overrides_canonical_product_id'), 'user_product_overrides', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_user_product_overrides_user_id'), 'user_product_overrides', ['user_id'], unique=False)
    op.create_table('product_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=False),
    sa.Column('canonical_product_id', sa.Integer(), nullable=False),
    sa.Column('matched_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_item_id')
    )
    op.create_index(op.f('ix_product_matches_canonical_product_id'), 'product_matches', ['canonical_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_matches_canonical_product_id'), table_name='product_matches')
    op.drop_table('product_matches')
    op.drop_index(op.f('ix_user_product_overrides_user_id'), table_name='user_product_overrides')
    op.drop_index(op.f('ix_user_product_overrides_canonical_product_id'), table_name='user_product_overrides')
    op.drop_table('user_product_overrides')
    op.drop_index(op.f('ix_user_product_categories_user_id'), table_name='user_product_categories')
    op.drop_index(op.f('ix_user_product_categories_custom_parent_id'), table_name='user_product_categories')
    op.drop_index(op.f('ix_user_product_categories_category_id'), table_name='user_product_categories')
    op.drop_table('user_product_categories')
    op.drop_index(op.f('ix_canonical_products_normalized_name'), table_name='canonical_products')
    op.drop_index(op.f('ix_canonical_products_fingerprint'), table_name='canonical_products')
    op.drop_index(op.f('ix_canonical_products_category_id'), table_name='canonical_products')
    op.drop_index(op.f('ix_canonical_products_brand'), table_name='canonical_products')
    op.drop_table('canonical_products')
    op.drop_index(op.f('ix_product_categories_parent_id'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
