"""change_invoice_unique_constraint_to_composite

Revision ID: b49e23560392
Revises: 25163688ecf3
Create Date: 2026-05-31 22:52:58.866880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49e23560392'
down_revision: Union[str, Sequence[str], None] = '25163688ecf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_source_url'), table_name='invoices')
    op.create_index(op.f('ix_invoices_source_url'), 'invoices', ['source_url'], unique=False)
    op.create_unique_constraint('uq_invoices_user_id_source_url', 'invoices', ['user_id', 'source_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoices_user_id_source_url', 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_source_url'), table_name='invoices')
    op.create_index(op.f('ix_invoices_source_url'), 'invoices', ['source_url'], unique=True)
    # ### end Alembic commands ###
